[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_endpoints = {sepolia = "", arb-sepolia = ""}

remapings = ["@openzeppelin/contracts=lib/openzeppelin-contracts/contracts", "@oeccip/=lib/ccip", "@chainlink-local/=lib/chainlink-local/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
